encoding: utf-8
lang: en-GB
# title: "SUD0X0"
description: "Blog about penetration testing and exploit writting."
url: "https://sud0x0.com"
baseurl: ""

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - CNAME
