title: SUD0X0
description: Blog about penetration testing and exploit writting.
url: https://sud0x0.com
baseurl: "/sud0x0"
permalink: /:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

gems:
  - jekyll-sitemap 
  - jekyll-feed

exclude:
  - CNAME
