title: SUD0X0
description: Blog about penetration testing and exploit writting.
url: "https://sud0x0.com"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins:
  - jekyll-sitemap 

exclude:
  - CNAME
